language: cpp

compiler:
  - clang
  - gcc

install:
    - sudo apt-get -y install ninja-build libboost-regex-dev

script:
    - mkdir build 
    - cd build && cmake .. -GNinja && ninja && ./unittests